# Generated by Django 3.2.21 on 2023-09-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
