# Generated by Django 3.2.21 on 2023-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_contactlist_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='birthday',
            field=models.DateTimeField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
